summarize_history:
  description: "Summarize this chat history concisely (100-300 tokens), focusing on key topics, user intents, and recent exchanges:\n{full_history}"
  expected_output: "A concise summary string (~100-300 tokens)."
  agent: summarizer

classify_query:
  description: "Classify if this query needs a direct response or agentic handling (tools/reasoning). Output JSON: {'mode': 'direct' or 'agentic'}. \nQuery: {user_query}\nSummarized history: {summarized_history}\nUser preferences (from {user_preferences_path}): {user_preferences}"
  expected_output: "JSON string."
  agent: classifier

generate_direct_response:
  description: "Generate a coherent, helpful response based on the query and context.\nQuery: {user_query}\nSummarized history: {summarized_history}\nUser preferences (from {user_preferences_path}): {user_preferences}"
  expected_output: "Final response string."
  agent: direct_responder

analyze_and_plan:
  description: "Analyze the query: Break into sub-tasks, identify needed operations/tools, flag ambiguities/errors. Output JSON: {'subtasks': [...], 'operations': [{'name': '...', 'params': {...}}], 'potential_issues': '...'}.\nQuery: {user_query}\nSummarized history: {summarized_history}\nUser preferences (from {user_preferences_path}): {user_preferences}\nAvailable operations (from {operations_file_path}): {available_operations}"
  expected_output: "JSON plan string."
  agent: analyzer_planner

refine_plan:
  description: "Review this plan for errors, feasibility, and completeness. Fix issues or flag if unresolvable. Output refined JSON plan or {'error': 'Need user clarification'}.\nPlan: {plan}\nAvailable operations (from {operations_file_path}): {available_operations}"
  expected_output: "Refined JSON string."
  agent: refiner

synthesize_response:
  description: "Synthesize these results into a coherent response. Include key outputs and explanations.\nQuery: {user_query}\nSummarized history: {summarized_history}\nUser preferences (from {user_preferences_path}): {user_preferences}\nOperation results: {op_results}"
  expected_output: "Final response string."
  agent: synthesizer
