analyze_and_plan:
  description: >
    Given the user query, chat history, user preferences, and operations file:
    - Match the query to the closest operation(s).
    - If found, return a JSON execution plan.
    - If not found, return a friendly unavailability message.
  expected_output: >
    EITHER:
    {
      "operations": [
        {
          "name": "<operation_name>",
          "parameters": { "<key>": "<value>" },
          "description": "Brief explanation"
        }
      ]
    }
    OR:
    "Sorry, I can't do that yet. This feature will be available soon."
  agent: analyzer
  output_file: execution_plan.json
