# FILE: src/agent_demo/config/tasks.yaml
analyze_project:
  description: Analyze user request and determine project requirements
  expected_output: JSON configuration for dynamic crew
  agent: analyzer